version: "3.7"

services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssqlserver
    volumes:
       - C:\dev\dotnet-environment\mssql:/var/opt/mssql/data
    ports: 
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SQL_PASSWORD}
      MSSQL_PID: ${SQL_PID}
    networks:
      - dev-network

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - dev-network
    depends_on: 
      - mssql-server
  
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - "8001:8001"
    volumes:
      - C:\dev\dotnet-environment\redisdb:/db
    depends_on:
      - redis
    networks:
      - dev-network
    
networks:
  dev-network:
    driver: bridge
    external: true
