version: "3.7"

services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: sql-server
    volumes:
      - /home/${USER_ROOT}/Dev/dotnet-environment/mssql:/var/opt/mssql/data
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SQL_PASSWORD: ${SQL_PASSWORD}
      SQL_PID: ${SQL_PID}
    networks:
      - devlx-network

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - devlx-network
    depends_on:
      - mssql-server

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - "8001:8001"
    volumes:
      - /home/${USER_ROOT}/Dev/dotnet-environment/redisdb:/db
    depends_on:
      - redis
    networks:
      - devlx-network

networks:
  devlx-network:
    driver: bridge
    external: true
